services:
  # MySQL数据库服务
  mysql:
    image: mysql:8.0
    container_name: ecommerce_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - ecommerce_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # 后端应用服务
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce_backend
    restart: unless-stopped
    environment:
      # 数据库配置
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_DATABASE: ecommerce_db
      # JWT配置
      JWT_SECRET: your_jwt_secret_key_for_production
      JWT_EXPIRES_IN: 1d
      # 服务器配置
      PORT: 3001
      NODE_ENV: production
    ports:
      - "3001:3001"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ecommerce_network
    volumes:
      - ./logs:/app/logs

# 数据卷
volumes:
  mysql_data:
    driver: local

# 网络
networks:
  ecommerce_network:
    driver: bridge