services:
  # MySQL数据库服务
  mysql:
    image: mysql:8.0
    container_name: ecommerce_mysql_simple
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_simple_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - ecommerce_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

# 数据卷
volumes:
  mysql_simple_data:
    driver: local

# 网络
networks:
  ecommerce_network:
    driver: bridge